--每日任务
DAILYTASK_ID = 0x00090000;
--老虎机模块头
SLOT_ID = 0x00530000
--金花manager消息
JINHUA_MGR_ID = 0x00680000
--manager消息头
MANAGER_ID = 0x00070000

DOUNIU_ID = 0x00220000;
DOUNIU_MGR_ID = 0x006e0000

--四川麻将MGR消息头
MJ_SC_MGR = 0x00740000;

--麻将大厅ID
MJ_HALL_ID = 0x00030000


--[[-----------------------新手任务模块DAILYTASK_ID 消息----------------------]]

--获取当前每日任务
DAILYTASKID_CURRENT_TASK = DAILYTASK_ID + 1;
--五星任务奖励
DAILYTASKID_FIVESTAR_AWARD = DAILYTASK_ID + 2;
--手动刷新任务
DAILYTASKID_REFRESH_TASK = DAILYTASK_ID + 3;
--立即完成
DAILYTASKID_COMPLETE_TASK = DAILYTASK_ID + 4;
--领取奖励
DAILYTASKID_GET_AWARD = DAILYTASK_ID + 5;
--任务状态变化
DAILYTASKID_TASK_STATUS_CHANGE = DAILYTASK_ID + 6;
--9.1.8获取新手奖励任务 (DAILYTASKID_NEW_USER_TASK)
DAILYTASKID_NEW_USER_TASK = DAILYTASK_ID + 8;
--9.1.9领取新手奖励 (DAILYTASKID_GET_NEW_USER_TASK_REWARD)
DAILYTASKID_GET_NEW_USER_TASK_REWARD = DAILYTASK_ID + 9;
--9.1.10新手奖励任务引导对话 (DAILYTASKID_NEW_USER_TASK_REWARD_GUIDE_PROMPT)
DAILYTASKID_NEW_USER_TASK_REWARD_GUIDE_PROMPT = DAILYTASK_ID + 10;

--[[-----------------------小游戏外部消息----------------------]]
--3.14.20小游戏获奖信息
MINI_COMMON_WINNING_RECORD =  SLOT_ID + 20
--3.14.21小游戏推荐
MINI_COMMON_RECOMMEND =  SLOT_ID + 21
--3.14.22小游戏引导(牌桌连胜和破产)
MINI_COMMON_NEWGUIDE = SLOT_ID + 22

--[[-----------------------金花manager消息----------------------]]


--3.04扎金花签到 (JINHUA_MGR_SIGN_V2）
--JINHUA_MGR_SIGN = JINHUA_MGR_ID + 4
JINHUA_MGR_SIGN_V2 = JINHUA_MGR_ID + 20
--3.05扎金花相关配置请求(JINHUA_MGR_SETTING）
--JINHUA_MGR_SETTING = JINHUA_MGR_ID + 5
--3.09扎金花送礼物 (JINHUA_MGR_SEND_GIFT）
--JINHUA_MGR_SEND_GIFT = JINHUA_MGR_ID + 9
--3.10扎金花个人信息消息 (JINHUA_MGR_USER_INFO）
--JINHUA_MGR_USER_INFO = JINHUA_MGR_ID + 10
--3.11购买金花VIP (JINHUA_MGR_BUY_VIP）
JINHUA_MGR_BUY_VIP = JINHUA_MGR_ID + 11
--3.18金花ios玩家添加推荐人好友 (JINHUA_MGR_JH_ADD _REFERRER）
JINHUA_MGR_JH_ADD_REFERRER = JINHUA_MGR_ID + 18
--3.25扎金花陌生人列表 (JINHUA_MGR_STRANGER_LIST）
JINHUA_MGR_STRANGER_LIST = JINHUA_MGR_ID + 25
--3.26扎金花每日领工资面板信息 (JINHUA_MGR_DAILY_SALARY）
JINHUA_MGR_DAILY_SALARY = JINHUA_MGR_ID + 26
--3.27扎金花领取每日工资 (JINHUA_MGR_GET_SALARY）
JINHUA_MGR_GET_SALARY = JINHUA_MGR_ID + 27


--4.2斗牛签到面板
DOUNIU_MGR_OPEN_SIGN = DOUNIU_MGR_ID + 2
--4.3斗牛签到
DOUNIU_MGR_SIGN = DOUNIU_MGR_ID + 3
--4.6 请求破产送金信息
DOUNIU_MGR_REVIVE_INFO = DOUNIU_MGR_ID + 6
--4.7 领取破产送金 (DOUNIU_MGR_REVIVE)
DOUNIU_MGR_REVIVE = DOUNIU_MGR_ID + 7
--4.8背包(DOUNIU_MGR_BACKPACK_ITEMS）
DOUNIU_MGR_BACKPACK_ITEMS = DOUNIU_MGR_ID + 8
--4.9使用背包物品(DOUNIU_USE_GIFT）
DOUNIU_USE_GIFT = DOUNIU_MGR_ID + 9
--4.10斗牛排行榜（DOUNIU_RANKLIST）
DOUNIU_RANKLIST = DOUNIU_MGR_ID + 10
--4.35月卡面板（DOUNIU_MONTH_CARD_V2）
DOUNIU_MONTH_CARD_V2 = DOUNIU_MGR_ID + 35
--4.12 VIP特权（DOUNIU_VIPINFO）
DOUNIU_VIPINFO = DOUNIU_MGR_ID + 12
--4.13斗牛充值返利相关信息
RECHARGE_REBATE_INFO = DOUNIU_MGR_ID + 13

--4.15好友列表
DOUNIU_MGR_FRIEND_LIST = DOUNIU_MGR_ID + 15
--4.16好友领取每日送金
DOUNIU_MGR_GET_FRIEND_COIN = DOUNIU_MGR_ID + 16

--2.122添加好友
DOUNIU_ADD_FRIEND = DOUNIU_ID + 122
--4.17添加好友
DOUNIU_MGR_ADD_FRIEND = DOUNIU_MGR_ID + 17
--4.18删除好友
DOUNIU_MGR_DEL_FRIEND = DOUNIU_MGR_ID + 18
--4.19添加追踪
DOUNIU_MGR_ADD_TRACE = DOUNIU_MGR_ID + 19
--4.20删除追踪 (DOUNIU_MGR_DEL_TRACE）
DOUNIU_MGR_DEL_TRACE = DOUNIU_MGR_ID + 20
--4.21执行追踪 (DOUNIU_MGR_DO_TRACE）
DOUNIU_MGR_DO_TRACE = DOUNIU_MGR_ID + 21
--4.22追踪列表
DOUNIU_MGR_TRACE_LIST = DOUNIU_MGR_ID + 22
--4.23同意加好友
DOUNIU_MGR_FRIEND_AGREE = DOUNIU_MGR_ID + 23
--4.24拒绝加好友
DOUNIU_MGR_FRIEND_REFUSE = DOUNIU_MGR_ID + 24

--4.25斗牛好友是否有红点
DOUNIU_MGR_FRIEND_HAVE_REDP = DOUNIU_MGR_ID + 25
--4.26斗牛绑定手机的金币奖励
DOUNIU_MGR_BINDPHONE_REWARDS = DOUNIU_MGR_ID + 26

--自建房间数据
DOUNIU_MGR_BUILD_TABLE_INFO = DOUNIU_MGR_ID + 27
--创建房间
DOUNIU_MGR_BUILD_TABLE = DOUNIU_MGR_ID + 28
--进入自建房
DOUNIU_MGR_ENTER_BUILD_TABLE = DOUNIU_MGR_ID + 29
--自建房倒计时广播
DOUNIU_MGR_BUILD_TABLE_COUNTDOWN_BROADCAST = DOUNIU_MGR_ID + 30
--自建房续桌广播
DOUNIU_MGR_BUILD_TABLE_CONTINUE_BROADCAST = DOUNIU_MGR_ID + 31
--请求有效自建房邀请码
DOUNIU_MGR_BUILD_TABLE_ROOMCODE = DOUNIU_MGR_ID + 32

--斗牛主页活动
DOUNIU_MGR_INDEX_ACTIVITY = DOUNIU_MGR_ID + 34








--------------------------------------------------
--1.4个人信息
MJ_SC_MGR_PLAYER_INFO = MJ_SC_MGR + 4;
--1.6大厅消息—大厅广播
MJ_SC_NOTICE = MJ_SC_MGR + 6;
--1.7大厅消息—微信分享
MJ_SC_SHARE_INFO = MJ_SC_MGR + 7;
-- 1.8大厅基础信息
MJ_SC_HALL_INFO = MJ_SC_MGR + 8;
--1.9推荐好友界面
MJ_SC_RECOMMEND_INFO = MJ_SC_MGR + 9;
--1.10推荐好友领奖界面
MJ_SC_RECEIVE_REWARD = MJ_SC_MGR + 10;
-- 3.9分享成功( ZIPAI_SHARING )
ZIPAI_SHARING = MJ_SC_MGR + 11;
--1.12房间记录
MJ_SC_MGR_ROOM_RECORD = MJ_SC_MGR + 12;
--1.13牌局记录
MJ_SC_MGR_INNING_RECORD = MJ_SC_MGR + 13;
--1.14获取牌局录像
MJ_SC_MGR_GET_ROOM_RECORD = MJ_SC_MGR + 14;
--1.15兑换码
MJ_SC_MGR_EXCHANGE_CODE = MJ_SC_MGR + 15;
--1.16更新房卡
MJ_SC_MGR_UPDATE_FANGKA = MJ_SC_MGR + 16;


--------------------------------------------
--3.1.2登录(MAHJONG_LOGIN)
MAHJONG_LOGIN = MJ_HALL_ID + 2
--3.1.3第三方渠道登录(MAHJONG_THIRD_PART_PLAT_LOGIN)
MAHJONG_THIRD_PART_PLAT_LOGIN = MJ_HALL_ID + 3