--四川麻将游戏头
MJ_SC_ID = 0x00570000;
--四川麻将MGR消息头
MJ_SC_MGR = 0x00740000;

--13.57.1牌桌变化(MJ_SC_GAME_TABLE_CHANGE)
MJ_SC_GAME_TABLE_CHANGE = MJ_SC_ID + 1;
--13.57.2准备/继续下局(MJ_SC_GAME_READY)
MJ_SC_GAME_READY = MJ_SC_ID + 2;
--13.57.3发牌(MJ_SC_GAME_SEND_CARD)
MJ_SC_GAME_SEND_CARD = MJ_SC_ID + 3;
--13.57.4打牌(MJ_SC_GAME_DISCARD)
MJ_SC_GAME_DISCARD = MJ_SC_ID + 4;
--13.57.5操作询问(MJ_SC_GAME_SEND_ACTION_OPTION)
MJ_SC_GAME_SEND_ACTION_OPTION = MJ_SC_ID + 5;
--13.57.6操作碰/杠/胡/过牌(MJ_SC_GAME_SELECT_ACTION_OPTION)
MJ_SC_GAME_SELECT_ACTION_OPTION = MJ_SC_ID + 6;
--13.57.7广播操作结果(MJ_SC_GAME_ACTION_BROADCAST)
MJ_SC_GAME_ACTION_BROADCAST = MJ_SC_ID + 7;
--13.57.8发一张牌【摸牌】(MJ_SC_GAME_DEAL_CARD)
MJ_SC_GAME_DEAL_CARD = MJ_SC_ID + 8;
--13.57.9提示玩家选择换三张(MJ_SC_GAME_SEND_CHANGE_CARD)
MJ_SC_GAME_SEND_CHANGE_CARD = MJ_SC_ID + 9;
--13.57.10换三张(MJ_SC_GAME_SELECT_CHANGE_CARD)
MJ_SC_GAME_SELECT_CHANGE_CARD = MJ_SC_ID + 10;
--13.57.11换三张结果(MJ_SC_GAME_CHANGE_CARD_BROADCAST)
MJ_SC_GAME_CHANGE_CARD_BROADCAST = MJ_SC_ID + 11;
--13.57.12提示玩家选择定缺(MJ_SC_GAME_SEND_DING_QUE)
MJ_SC_GAME_SEND_DING_QUE = MJ_SC_ID + 12;
--13.57.13玩家定缺(MJ_SC_GAME_SELECT_DING_QUE)
MJ_SC_GAME_SELECT_DING_QUE = MJ_SC_ID + 13;
--13.57.14广播定缺结果(MJ_SC_GAME_DINGQUE_BROADCAST)
MJ_SC_GAME_DINGQUE_BROADCAST = MJ_SC_ID + 14;
--13.57.15听牌方案列表(MJ_SC_GAME_TING_SOLUTIONS)
MJ_SC_GAME_TING_SOLUTIONS = MJ_SC_ID + 15;
--13.57.16听牌状态变更(MJ_SC_GAME_TING_STATUS_CHANGED)
MJ_SC_GAME_TING_STATUS_CHANGED = MJ_SC_ID + 16;
--13.57.17游戏结果(MJ_SC_GAME_GAME_RESULT)
MJ_SC_GAME_GAME_RESULT = MJ_SC_ID + 17;
--13.57.18房间总结果(MJ_SC_GAME_ROOM_RESULT)
MJ_SC_GAME_ROOM_RESULT = MJ_SC_ID + 18;
--13.57.19续玩通知(MJ_SC_GAME_RECONNECT_NOTIFY)
MJ_SC_GAME_RECONNECT_NOTIFY = MJ_SC_ID + 19;
--13.57.20牌桌同步(MJ_SC_GAME_SYNC_TABLE)
MJ_SC_GAME_SYNC_TABLE = MJ_SC_ID + 20;
--13.57.21解散房间申请(MJ_SC_GAME_DISMISS_ROOM)
MJ_SC_GAME_DISMISS_ROOM = MJ_SC_ID + 21;
--13.57.22解散房间投票(MJ_SC_GAME_DISMISS_VOTE)
MJ_SC_GAME_DISMISS_VOTE = MJ_SC_ID + 22;
--13.57.23同步自己的手牌(MJ_SC_GAME_SYNC_HAND_CARDS)
MJ_SC_GAME_SYNC_HAND_CARDS = MJ_SC_ID + 23;
--13.57.24推送用户游戏状态(MJ_SC_GAME_PUSH_PLAYER_STATE)
MJ_SC_GAME_PUSH_PLAYER_STATE = MJ_SC_ID + 24;
--13.57.25广播胡牌结果(MJ_SC_GAME_HU_RESULT_BROADCAST)
MJ_SC_GAME_HU_RESULT_BROADCAST = MJ_SC_ID + 25;


--13.57.101进入房间(MJ_SC_ROOM_ENTER_ROOM)
MJ_SC_ROOM_ENTER_ROOM = MJ_SC_ID + 101;
--13.57.102聊天
MJ_SC_ROOM_CHAT = MJ_SC_ID + 102;
--13.57.103距离警告
MJ_SC_DISTANCE_ALERT = MJ_SC_ID + 103;
--13.57.104 牌桌内个人信息
MJ_SC_MGR_PLAYER_INFO_IN_TABLE = MJ_SC_ID + 104;
--13.57.105赠送魔法表情
MJ_SC_SEND_MAGIC = MJ_SC_ID + 105;
--13.57.106牌桌飞礼物消息
MJ_SC_BROADCAST_FLY_GIFT = MJ_SC_ID + 106;


------------------------------------------------------
--1.1进入房间
MJ_SC_MGR_ENTER_ROOM = MJ_SC_MGR + 1
--1.2退出房间
MJ_SC_MGR_QUIT_ROOM = MJ_SC_MGR + 2
--1.3建立房间
MJ_SC_MGR_CREATE_ROOM = MJ_SC_MGR + 3;
-- 1.5牌桌选项
MJ_SC_MGR_CREATE_OPTION = MJ_SC_MGR + 5;

